#!/bin/bash
# reduce-spike-plan.sh — Regenerate the auto-generated ticket registry (§7)
# inside <repo>/docs/plan/<epicId>/spike-plan.md from events.jsonl.
#
# Source of truth: events.jsonl. Writer: between sentinel markers only.
# Outside-sentinel content is preserved verbatim.
#
# Sentinel markers (must exist in spike-plan.md):
#   <!-- BEGIN AUTO-GENERATED REGISTRY -->
#   <!-- END AUTO-GENERATED REGISTRY -->
#
# No-op conditions:
#   - events.jsonl missing or empty
#   - No epicId in session.started or progress-log.json
#   - spike-plan.md missing at <repo>/docs/plan/<epicId>/spike-plan.md
#   - Sentinels missing in spike-plan.md
#
# Safe to call as often as desired (idempotent, atomic write).

set -uo pipefail
trap 'exit 0' ERR

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./_session-lib.sh
. "$SCRIPT_DIR/_session-lib.sh"
# shellcheck source=./_reducers.sh
. "$SCRIPT_DIR/_reducers.sh"

command -v jq &>/dev/null || exit 0

EVENTS=$(events_file)
[ -f "$EVENTS" ] || exit 0

# Resolve epicId: prefer progress-log.json, fall back to last session.started event.
SESSION_DIR=$(resolve_session_dir)
PROGRESS_LOG="$SESSION_DIR/progress-log.json"
EPIC_ID=""
if [ -f "$PROGRESS_LOG" ]; then
    EPIC_ID=$(jq -r '.epicId // empty' "$PROGRESS_LOG" 2>/dev/null)
fi
if [ -z "$EPIC_ID" ]; then
    EPIC_ID=$(jq -rs '[.[] | select(.type == "session.started") | .data.epicId // empty] | last // empty' "$EVENTS" 2>/dev/null)
fi
[ -n "$EPIC_ID" ] || exit 0

# Resolve plan doc path: <repo>/docs/plan/<epicId>/spike-plan.md
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
[ -n "$REPO_ROOT" ] || exit 0
PLAN_DOC="$REPO_ROOT/docs/plan/$EPIC_ID/spike-plan.md"
[ -f "$PLAN_DOC" ] || exit 0

# Verify sentinels present. If not, the plan doc was hand-authored before the
# reducer existed; do nothing rather than corrupt the file.
grep -qF '<!-- BEGIN AUTO-GENERATED REGISTRY -->' "$PLAN_DOC" || exit 0
grep -qF '<!-- END AUTO-GENERATED REGISTRY -->'   "$PLAN_DOC" || exit 0

# Fold over events.jsonl to build the ticket registry:
#   - ticket.decomposed initializes a row (status=planned) and records blockers.
#     Latest decomposed for a ticketId supersedes prior (Phase-4 reclassification).
#   - ticket.started advances status to in-impl.
#   - ticket.merged advances status to merged.
# Output: a markdown table body (header separate, written below).
TABLE_ROWS=$(jq -rs --arg epic "$EPIC_ID" '
    # Filter to events for this epic
    def belongs_to_epic(e): e.data.epicId == $epic;

    # Latest ticket.decomposed per ticketId
    def latest_decomposed:
        [ .[] | select(.type == "ticket.decomposed" and belongs_to_epic(.)) ]
        | group_by(.data.ticketId)
        | map(max_by(.seq));

    # Status resolver per ticketId: merged > in-impl > planned
    def status_of($tid):
        if any(.[]; .type == "ticket.merged" and belongs_to_epic(.) and .data.ticketId == $tid)
        then "merged"
        elif any(.[]; .type == "ticket.started" and belongs_to_epic(.) and .data.ticketId == $tid)
        then "in-impl"
        else "planned"
        end;

    # Render a blocker list as comma-joined [ticketId] form (kind-unaware at table level).
    def render_blockers($list):
        if ($list | length) == 0 then "[]"
        else "[" + ([$list[] | .ticketId] | join(", ")) + "]"
        end;

    . as $all
    | ($all | latest_decomposed) as $tickets
    | $tickets
    | map(
        . as $t
        | {
            id: $t.data.ticketId,
            title: ($t.data.title // ""),
            status: ($all | status_of($t.data.ticketId)),
            implBlockers: render_blockers($t.data.implBlockedBy // []),
            deployBlockers: render_blockers($t.data.deployBlockedBy // []),
            ref: ($t.data.ticketId + ".md")
          }
      )
    | sort_by(.id)
    | if length == 0 then "" else
        (map("| \(.id) | \(.title) | \(.status) | \(.implBlockers) | \(.deployBlockers) | [\(.id)](\(.ref)) |") | join("\n"))
      end
' "$EVENTS" 2>/dev/null) || exit 0

# Rebuild the plan doc with the new registry section replaced between sentinels.
# AWK-based replacement so we never load the whole file into jq.
BEGIN_MARK='<!-- BEGIN AUTO-GENERATED REGISTRY -->'
END_MARK='<!-- END AUTO-GENERATED REGISTRY -->'
REGEN_AT=$(iso_utc)

# Compose the replacement block content. `|| :` protects against empty TABLE_ROWS.
REPLACEMENT=$(
    printf '%s\n' "$BEGIN_MARK"
    printf '<!-- Regenerated by reduce-spike-plan.sh at %s -->\n' "$REGEN_AT"
    printf '| ID | Title | Status | impl-blockedBy | deploy-blockedBy | Ref |\n'
    printf '|----|-------|--------|----------------|------------------|-----|\n'
    if [ -n "$TABLE_ROWS" ]; then printf '%s\n' "$TABLE_ROWS"; fi
    printf '%s\n' "$END_MARK"
)

awk -v BEGIN_MARK="$BEGIN_MARK" -v END_MARK="$END_MARK" -v REPLACEMENT="$REPLACEMENT" '
    BEGIN { skip = 0 }
    index($0, BEGIN_MARK) { print REPLACEMENT; skip = 1; next }
    index($0, END_MARK)   { skip = 0; next }
    skip == 0 { print }
' "$PLAN_DOC" | atomic_write "$PLAN_DOC"

exit 0
